In [67]:
!pip install jsonlines
import pandas as pd

Requirement already satisfied: jsonlines in c:\users\senth\anaconda3\lib\site-packages (3.1.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\senth\anaconda3\lib\site-packages (from jsonlines) (21.4.0)

In [105]:
with open('test.src', 'r', encoding='utf') as src_file:
    data = src_file.readlines()

In [106]:
df = pd.DataFrame(data, columns=['src_content'])

In [107]:
df

                                            src_content
0     GOP Eyes Gains As Voters In 11 States Pick Gov...
1     NEWLINE_CHAR  NEWLINE_CHAR  NEWLINE_CHAR  NEWL...
2     It's the Golden State's latest version of the ...
3     The seed for this crawl was a list of every ho...
4     After a year in which liberals scored impressi...
...                                                 ...
5617  Tweet with a location NEWLINE_CHAR  NEWLINE_CH...
5618  Loic Venance/AFP/Getty Images NEWLINE_CHAR  NE...
5619  (CNN) A federal criminal investigation into a ...
5620  An archive of the public statements deleted by...
5621  An apparently simple email about a holiday pot...

[5622 rows x 1 columns]

In [108]:
with open('test.tgt', 'r', encoding='utf') as tgt_file:
    datatgt = tgt_file.readlines()

In [109]:
df1 = pd.DataFrame(datatgt, columns=['tgt_content'])

In [110]:
df1

                                            tgt_content
0     – It's a race for the governor's mansion in 11...
1     – It turns out Facebook is only guilty of abou...
2     – Not a big fan of Southern California? Neithe...
3     – Why did Microsoft buy Nokia's phone business...
4     – The Supreme Court is facing a docket of high...
...                                                 ...
5617  – The traditional end-of-summit group photo at...
5618  – Sofia Coppola scored a historic victory at t...
5619  – The duck boat sinking that killed 17 on a Mi...
5620  – Note to tweeting politicians: Watch what you...
5621  – "STOP THE MADNESS!!!!," "dear lord," and "I ...

[5622 rows x 1 columns]

In [111]:
# Combine summaries and sources into a single DataFrame
combined_df = pd.concat([df, df1], axis=1)

In [112]:
combined_df

,src_content,tgt_content
0,GOP Eyes Gains As Voters In 11 States Pick Gov...,– It's a race for the governor's mansion in 11...
1,NEWLINE_CHAR NEWLINE_CHAR NEWLINE_CHAR NEWL...,– It turns out Facebook is only guilty of abou...
2,It's the Golden State's latest version of the ...,– Not a big fan of Southern California? Neithe...
3,The seed for this crawl was a list of every ho...,– Why did Microsoft buy Nokia's phone business...
4,After a year in which liberals scored impressi...,– The Supreme Court is facing a docket of high...
...,...,...
5617,Tweet with a location NEWLINE_CHAR NEWLINE_CH...,– The traditional end-of-summit group photo at...
5618,Loic Venance/AFP/Getty Images NEWLINE_CHAR NE...,– Sofia Coppola scored a historic victory at t...
5619,(CNN) A federal criminal investigation into a ...,– The duck boat sinking that killed 17 on a Mi...
5620,An archive of the public statements deleted by...,– Note to tweeting politicians: Watch what you...
5621,An apparently simple email about a holiday pot...,"– ""STOP THE MADNESS!!!!,"" ""dear lord,"" and ""I ..."

In [113]:
Truncated_data = combined_df.head(1000)

In [114]:
Truncated_data

,src_content,tgt_content
0,GOP Eyes Gains As Voters In 11 States Pick Gov...,– It's a race for the governor's mansion in 11...
1,NEWLINE_CHAR NEWLINE_CHAR NEWLINE_CHAR NEWL...,– It turns out Facebook is only guilty of abou...
2,It's the Golden State's latest version of the ...,– Not a big fan of Southern California? Neithe...
3,The seed for this crawl was a list of every ho...,– Why did Microsoft buy Nokia's phone business...
4,After a year in which liberals scored impressi...,– The Supreme Court is facing a docket of high...
...,...,...
995,Anticipating a month of heavy lobbying and tel...,– President Obama today began his campaign to ...
996,Wayne Flynt was a close friend of Harper Lee u...,– In the soon-to-be published contents of a de...
997,Men who found missing Riverbank woman tell the...,– A former kindergarten teacher last heard fro...
998,Men sit outside the Raymond G. Murphy VA Medic...,– Another black eye for the Veterans Health Ad...
999,"An attorney for the Texas teen who cited ""affl...","– The US teen diagnosed with ""affluenza"" will ..."

In [115]:
#Removing Paranthesis and Hyphens
Truncated_data['src_content'] = Truncated_data['src_content'].str.replace(r'[\(\)\-]','', regex=True)

C:\Users\senth\AppData\Local\Temp\ipykernel_19292\2331838389.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Truncated_data['src_content'] = Truncated_data['src_content'].str.replace(r'[\(\)\-]','', regex=True)

In [116]:
Truncated_data

,src_content,tgt_content
0,GOP Eyes Gains As Voters In 11 States Pick Gov...,– It's a race for the governor's mansion in 11...
1,NEWLINE_CHAR NEWLINE_CHAR NEWLINE_CHAR NEWL...,– It turns out Facebook is only guilty of abou...
2,It's the Golden State's latest version of the ...,– Not a big fan of Southern California? Neithe...
3,The seed for this crawl was a list of every ho...,– Why did Microsoft buy Nokia's phone business...
4,After a year in which liberals scored impressi...,– The Supreme Court is facing a docket of high...
...,...,...
995,Anticipating a month of heavy lobbying and tel...,– President Obama today began his campaign to ...
996,Wayne Flynt was a close friend of Harper Lee u...,– In the soon-to-be published contents of a de...
997,Men who found missing Riverbank woman tell the...,– A former kindergarten teacher last heard fro...
998,Men sit outside the Raymond G. Murphy VA Medic...,– Another black eye for the Veterans Health Ad...
999,"An attorney for the Texas teen who cited ""affl...","– The US teen diagnosed with ""affluenza"" will ..."

In [128]:
Truncated_data['tgt_content'] = Truncated_data['tgt_content'].str.replace(r'[\(\)\–]', '', regex=True)

C:\Users\senth\AppData\Local\Temp\ipykernel_19292\1257641038.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Truncated_data['tgt_content'] = Truncated_data['tgt_content'].str.replace(r'[\(\)\–]', '', regex=True)

In [129]:
Truncated_data

,src_content,tgt_content
0,GOP Eyes Gains As Voters In 11 States Pick Gov...,It's a race for the governor's mansion in 11 ...
1,UPDATE: 4/19/2001 Read Richard Metzger:...,It turns out Facebook is only guilty of about...
2,It's the Golden State's latest version of the ...,Not a big fan of Southern California? Neither...
3,The seed for this crawl was a list of every ho...,Why did Microsoft buy Nokia's phone business?...
4,After a year in which liberals scored impressi...,The Supreme Court is facing a docket of highp...
...,...,...
995,Anticipating a month of heavy lobbying and tel...,President Obama today began his campaign to c...
996,Wayne Flynt was a close friend of Harper Lee u...,In the soontobe published contents of a decad...
997,Men who found missing Riverbank woman tell the...,A former kindergarten teacher last heard from...
998,Men sit outside the Raymond G. Murphy VA Medic...,Another black eye for the Veterans Health Adm...
999,"An attorney for the Texas teen who cited ""affl...","The US teen diagnosed with ""affluenza"" will n..."

In [130]:
def remove_word(Truncated_data, src_content, word):
    Truncated_data['src_content'] = Truncated_data['src_content'].str.replace(word, '')
    return Truncated_data
word_to_remove = 'NEWLINE_CHAR'
column_name = 'src_content'
Truncated_data = remove_word(Truncated_data,column_name,word_to_remove)

C:\Users\senth\AppData\Local\Temp\ipykernel_19292\3619561271.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Truncated_data['src_content'] = Truncated_data['src_content'].str.replace(word, '')

In [131]:
Truncated_data

,src_content,tgt_content
0,GOP Eyes Gains As Voters In 11 States Pick Gov...,It's a race for the governor's mansion in 11 ...
1,UPDATE: 4/19/2001 Read Richard Metzger:...,It turns out Facebook is only guilty of about...
2,It's the Golden State's latest version of the ...,Not a big fan of Southern California? Neither...
3,The seed for this crawl was a list of every ho...,Why did Microsoft buy Nokia's phone business?...
4,After a year in which liberals scored impressi...,The Supreme Court is facing a docket of highp...
...,...,...
995,Anticipating a month of heavy lobbying and tel...,President Obama today began his campaign to c...
996,Wayne Flynt was a close friend of Harper Lee u...,In the soontobe published contents of a decad...
997,Men who found missing Riverbank woman tell the...,A former kindergarten teacher last heard from...
998,Men sit outside the Raymond G. Murphy VA Medic...,Another black eye for the Veterans Health Adm...
999,"An attorney for the Texas teen who cited ""affl...","The US teen diagnosed with ""affluenza"" will n..."

In [132]:
import re

def remove_emails_websites(text):
    # Remove email addresses
    text = re.sub(r'\S+@\S+', '', text)
    
    # Remove website links starting with http:// or https://
    text = re.sub(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', '', text)
    
    return text

In [133]:
Truncated_data['src_content'] = Truncated_data['src_content'].apply(remove_emails_websites)

C:\Users\senth\AppData\Local\Temp\ipykernel_19292\1378552616.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Truncated_data['src_content'] = Truncated_data['src_content'].apply(remove_emails_websites)

In [134]:
Truncated_data

,src_content,tgt_content
0,GOP Eyes Gains As Voters In 11 States Pick Gov...,It's a race for the governor's mansion in 11 ...
1,UPDATE: 4/19/2001 Read Richard Metzger:...,It turns out Facebook is only guilty of about...
2,It's the Golden State's latest version of the ...,Not a big fan of Southern California? Neither...
3,The seed for this crawl was a list of every ho...,Why did Microsoft buy Nokia's phone business?...
4,After a year in which liberals scored impressi...,The Supreme Court is facing a docket of highp...
...,...,...
995,Anticipating a month of heavy lobbying and tel...,President Obama today began his campaign to c...
996,Wayne Flynt was a close friend of Harper Lee u...,In the soontobe published contents of a decad...
997,Men who found missing Riverbank woman tell the...,A former kindergarten teacher last heard from...
998,Men sit outside the Raymond G. Murphy VA Medic...,Another black eye for the Veterans Health Adm...
999,"An attorney for the Texas teen who cited ""affl...","The US teen diagnosed with ""affluenza"" will n..."

In [135]:
Truncated_data['tgt_content'] = Truncated_data['tgt_content'].apply(remove_emails_websites)

C:\Users\senth\AppData\Local\Temp\ipykernel_19292\2670071125.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Truncated_data['tgt_content'] = Truncated_data['tgt_content'].apply(remove_emails_websites)

In [136]:
Truncated_data

,src_content,tgt_content
0,GOP Eyes Gains As Voters In 11 States Pick Gov...,It's a race for the governor's mansion in 11 ...
1,UPDATE: 4/19/2001 Read Richard Metzger:...,It turns out Facebook is only guilty of about...
2,It's the Golden State's latest version of the ...,Not a big fan of Southern California? Neither...
3,The seed for this crawl was a list of every ho...,Why did Microsoft buy Nokia's phone business?...
4,After a year in which liberals scored impressi...,The Supreme Court is facing a docket of highp...
...,...,...
995,Anticipating a month of heavy lobbying and tel...,President Obama today began his campaign to c...
996,Wayne Flynt was a close friend of Harper Lee u...,In the soontobe published contents of a decad...
997,Men who found missing Riverbank woman tell the...,A former kindergarten teacher last heard from...
998,Men sit outside the Raymond G. Murphy VA Medic...,Another black eye for the Veterans Health Adm...
999,"An attorney for the Texas teen who cited ""affl...","The US teen diagnosed with ""affluenza"" will n..."

In [137]:
#Removing special character from dataframe
Truncated_data = Truncated_data.replace('[^\w\s]', '', regex=True)

In [138]:
Truncated_data

,src_content,tgt_content
0,GOP Eyes Gains As Voters In 11 States Pick Gov...,Its a race for the governors mansion in 11 st...
1,UPDATE 4192001 Read Richard Metzger How...,It turns out Facebook is only guilty of about...
2,Its the Golden States latest version of the Gr...,Not a big fan of Southern California Neither ...
3,The seed for this crawl was a list of every ho...,Why did Microsoft buy Nokias phone business W...
4,After a year in which liberals scored impressi...,The Supreme Court is facing a docket of highp...
...,...,...
995,Anticipating a month of heavy lobbying and tel...,President Obama today began his campaign to c...
996,Wayne Flynt was a close friend of Harper Lee u...,In the soontobe published contents of a decad...
997,Men who found missing Riverbank woman tell the...,A former kindergarten teacher last heard from...
998,Men sit outside the Raymond G Murphy VA Medica...,Another black eye for the Veterans Health Adm...
999,An attorney for the Texas teen who cited afflu...,The US teen diagnosed with affluenza will now...

In [139]:
Truncated_data.to_csv('Test_Truncated_Data.csv', index=False)